config/routes.rb
Rails.application.routes.draw do
  resources :job_openings
  resources :companies

  root to: "landing#index"
  get "search", to: "landing#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :job_openings
end

app/models/job_opening.rb
class JobOpening < ApplicationRecord

  TECH = %w(ruby javascript python java html css ios android sphinx es6 coffeescript react redux )
  RESPONSIBILITIES = %w(deliver maintain development deploy manage lead design sales mobile collaborate cross-functional)
  FIELDS = %w(security machine\ learning infrastructure performance data\ science desktop web mobile frontend backend full\ stack devops design)

  belongs_to :company

  include PgSearch
   pg_search_scope :search,
      associated_against: {
        company: [:name]
      },
      against: [:title, :location, :team], using: {
        tsearch: {:prefix => true},
        trigram: {},
        dmetaphone: {}
      }

    pg_search_scope :search_exact,
      against: [:description], using: {
        tsearch: {:prefix => true},
      }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "ycombinatortest", password: "ycombinatortest"

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :url, :jobs_url, :logo)
    end
end

app/controllers/job_openings_controller.rb
class JobOpeningsController < ApplicationController
  before_action :set_job_opening, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "ycombinatortest", password: "ycombinatortest"

  # GET /job_openings
  # GET /job_openings.json
  def index
    @job_openings = JobOpening.all
  end

  # GET /job_openings/1
  # GET /job_openings/1.json
  def show
  end

  # GET /job_openings/new
  def new
    @job_opening = JobOpening.new
  end

  # GET /job_openings/1/edit
  def edit
  end

  # POST /job_openings
  # POST /job_openings.json
  def create
    @job_opening = JobOpening.new(job_opening_params)

    respond_to do |format|
      if @job_opening.save
        format.html { redirect_to @job_opening, notice: 'Job opening was successfully created.' }
        format.json { render :show, status: :created, location: @job_opening }
      else
        format.html { render :new }
        format.json { render json: @job_opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_openings/1
  # PATCH/PUT /job_openings/1.json
  def update
    respond_to do |format|
      if @job_opening.update(job_opening_params)
        format.html { redirect_to @job_opening, notice: 'Job opening was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_opening }
      else
        format.html { render :edit }
        format.json { render json: @job_opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_openings/1
  # DELETE /job_openings/1.json
  def destroy
    @job_opening.destroy
    respond_to do |format|
      format.html { redirect_to job_openings_url, notice: 'Job opening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_opening
      @job_opening = JobOpening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_opening_params
      params.require(:job_opening).permit(:title, :locations, :commitment, :team, :description, :salary)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @jobs = JobOpening.joins(:company).distinct.includes(:company)
    @jobs_count = @jobs.count
  end

  def search
    query = params[:q]
    tags = params[:tags] || []
    company_exclusions = params[:companies] || []

    relation = JobOpening.where.not(company_id: company_exclusions)
    @jobs = if(query.present? && tags.present?)
      relation.search(query).search_exact(tags)
    elsif query.present? && !tags.present?
      relation.search(query)
    elsif tags.present?
      relation.search_exact(tags)
    else
      relation.joins(:company).distinct.includes(:company)
    end

    @jobs.preload(:company)
    @jobs_count = @jobs.count

    render template: "landing/_jobs", locals: {  jobs_count: @jobs_count, jobs: @jobs }, layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/job_openings_helper.rb
module JobOpeningsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :company_url %>
  </div>

  <div class="field">
    <%= form.label :jobs_url %>
    <%= form.text_field :jobs_url, id: :company_jobs_url %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo, id: :company_logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Jobs url</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.url %></td>
        <td><%= company.jobs_url %></td>
        <td><%= company.logo %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company.url %>
</p>

<p>
  <strong>Jobs url:</strong>
  <%= @company.jobs_url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @company.logo %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/job_openings/_form.html.erb
<%= form_with(model: job_opening, local: true) do |form| %>
  <% if job_opening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_opening.errors.count, "error") %> prohibited this job_opening from being saved:</h2>

      <ul>
      <% job_opening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_opening_title %>
  </div>

  <div class="field">
    <%= form.label :locations %>
    <%= form.text_field :locations, id: :job_opening_locations %>
  </div>

  <div class="field">
    <%= form.label :commitment %>
    <%= form.text_field :commitment, id: :job_opening_commitment %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team, id: :job_opening_team %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :job_opening_description %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary, id: :job_opening_salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_openings/edit.html.erb
<h1>Editing Job Opening</h1>

<%= render 'form', job_opening: @job_opening %>

<%= link_to 'Show', @job_opening %> |
<%= link_to 'Back', job_openings_path %>

app/views/job_openings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Openings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Locations</th>
      <th>Commitment</th>
      <th>Team</th>
      <th>Description</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_openings.each do |job_opening| %>
      <tr>
        <td><%= job_opening.title %></td>
        <td><%= job_opening.location %></td>
        <td><%= job_opening.commitment %></td>
        <td><%= job_opening.team %></td>
        <td><%= job_opening.description %></td>
        <td><%= job_opening.salary %></td>
        <td><%= link_to 'Show', job_opening %></td>
        <td><%= link_to 'Edit', edit_job_opening_path(job_opening) %></td>
        <td><%= link_to 'Destroy', job_opening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job Opening', new_job_opening_path %>

app/views/job_openings/new.html.erb
<h1>New Job Opening</h1>

<%= render 'form', job_opening: @job_opening %>

<%= link_to 'Back', job_openings_path %>

app/views/job_openings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job_opening.title %>
</p>

<p>
  <strong>Locations:</strong>
  <%= @job_opening.location %>
</p>

<p>
  <strong>Commitment:</strong>
  <%= @job_opening.commitment %>
</p>

<p>
  <strong>Team:</strong>
  <%= @job_opening.team %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_opening.description %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job_opening.salary %>
</p>

<%= link_to 'Edit', edit_job_opening_path(@job_opening) %> |
<%= link_to 'Back', job_openings_path %>

app/views/landing/_jobs.html.erb
<h3><%= jobs_count %> Job Openings </h3>
<div class="row jobs">
  <% if jobs.size == 0 %>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12"><p class="lead"> No Jobs found with this criteria </p></div>
  <% end %>
  <% jobs.map do |job| %>
    <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 ">
      <div class="thumbnail job">
        <div class="caption">
          <h4 class="job_title single_line"><a target="_blank" href=<%= job.url %>><%= job.title %></a></h4>
          <p>
            <span class="text-muted">by </span>
            <a target="_blank" data-id=<%=job.company.id%> href=<%= job.company.url %>><%= job.company.name %></a>
            <small><a href="#" class="exclude_company text-danger" data-name=<%= job.company.name %> data-id=<%=job.company.id%>>(exclude company)</a></small>
          </p>
          <p>
            <span class="label label-primary"><%= job.team %></span>
            <span class="label label-success"><%= job.location %></span>
          </p>
          <p class="job_description"><%= truncate(job.description, length: 180) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/landing/_tags.html.erb
<div class="tags_row">
  <% colors = ["primary", "warning", "danger", "success"] %>
  <% tags.each_with_index do |tag, i| %>
    <span data-tag=<%= tag %> class="tech_btn btn btn-outline btn-sm btn-<%= colors[i % 4] %>"><%= tag %></span>
  <% end %>
</div>

app/views/landing/index.html.erb
<div class="home">
  <div class="header_section">
    <div class="container">
      <div class="jumbotron bg-ycombinator">
        <h1> Find YCombinator Startups Jobs </h1>
        <p class="lead"> Search and filter job openings by YCombinator startups </p>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row sticky_parent">
      <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
        <div class="jobs_container">
          <%= render 'jobs', jobs: @jobs, jobs_count: @jobs_count %>
        </div>
      </div>

        <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
          <div class="stick_in_parent search_sticky">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="search_controls">
                <div class="form-group search_box">
                  <label class="text-muted">Filter Job Openings</label>
                  <input type="text" class="input-sm form-control insta_search" placeholder="Filter by title, location, company or team...">
                </div>

                <div class="tags">
                  <label class="text-muted">Tech & Stack</label>
                  <%= render 'tags', tags: JobOpening::TECH %>
                  <label class="text-muted">Responsibilities</label>
                  <%= render 'tags', tags: JobOpening::RESPONSIBILITIES %>
                  <label class="text-muted">Fields</label>
                  <%= render 'tags', tags: JobOpening::FIELDS %>
                </div>
                <label class="text-muted"> Excluded Companies </label>
                <div class="excluded_companies">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YC Startup Jobs</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">YC Startup Jobs</a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>